version: 0.0
os: linux
files:
  - source: /dist # Source directory or files to be copied to the target directory
    destination: /var/www/mi.zinterview.ai # Target directory on the EC2 instance
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
